package application;

import java.io.IOException;

import java.lang.System.Logger;
import java.lang.System.Logger.Level;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.layout.AnchorPane;
import javafx.scene.Parent;
import javafx.scene.input.MouseEvent;

import javafx.scene.layout.BorderPane;

import java.net.URL;
import java.sql.Date;
import java.util.ResourceBundle;

import DAO.DepartamentoDao;
import DAO.EmpleadoDao;
import Model.Empleado;
import Model.Empresa;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;
import javafx.scene.control.DatePicker;
import javafx.scene.control.TextField;
import javafx.stage.StageStyle;

public class MenuController {
	@FXML
	private BorderPane bp;
	@FXML
	private AnchorPane ap;

	// Event Listener on Button.onMouseClicked
	@FXML
	public void home(MouseEvent event) {
		// TODO Autogenerated
		bp.setCenter(ap);
	}
	// Event Listener on Button.onMouseClicked
	@FXML
	public void pag1(MouseEvent event) {
		// TODO Autogenerated
		loadPage("page1");
	}
	// Event Listener on Button.onMouseClicked
	@FXML
	public void pag2(MouseEvent event) {
		// TODO Autogenerated
		loadPage("page2");
	}
	
	@FXML
	public void pag3(MouseEvent event) {
		// TODO Autogenerated
		loadPage("page3");
	}
	
	@FXML
	public void pag4(MouseEvent event) {
		// TODO Autogenerated
		loadPage("page4");
	}
	
	@FXML
	public void pag5(MouseEvent event) {
		// TODO Autogenerated
		loadPage("page5");
	}
	private void loadPage (String page) {
		Parent root = null;
		
	
		try {
			root = FXMLLoader.load(getClass().getResource(page+".fxml"));
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		bp.setCenter(root);
	}
}
