package application;

import javafx.fxml.FXML;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

public class Page5Controller {
	@FXML
	private TextField txtNombreEmp;
	@FXML
	private TextField txtApellidoPaterno;

	// Event Listener on Button.onAction
	@FXML
	public void btnGuardarEmpleadoOnAction(ActionEvent event) {
		// TODO Autogenerated
	}
}
