package application;

import javafx.fxml.FXML;

import javafx.scene.control.TextField;
import javafx.stage.StageStyle;

import java.sql.Date;

import DAO.DepartamentoDao;
import DAO.EmpleadoDao;
import Model.Empleado;
import Model.Empresa;
import javafx.event.ActionEvent;
import javafx.scene.control.Alert;
import javafx.scene.control.DatePicker;

public class Page2Controller {
	@FXML
	private TextField txtNombreEmp;
	@FXML
    private TextField txtNombre;
	@FXML
	private TextField txtApellidoPaterno;
	@FXML
	private TextField txtApellidoMaterno;
	@FXML
	private DatePicker txtFechaNacimiento;
	@FXML
	private TextField txtDepartamento;
	@FXML
	private EmpleadoDao	empleadoDao;
	@FXML
    void initialize() {
        this.empleadoDao=new EmpleadoDao();
    }

	// Event Listener on Button.onAction
	@FXML
	public void btnGuardarEmpleadoOnAction(ActionEvent event) {
		// TODO Autogenerated
    	Empleado empleado = new Empleado();
    	
    	empleado.setNombre(txtNombreEmp.getText());
    	empleado.setAppaterno(txtApellidoPaterno.getText());
    	empleado.setApmaterno(txtApellidoMaterno.getText());
    	empleado.setFecha_nacimiento(Date.valueOf(txtFechaNacimiento.getValue()));
    	empleado.setDepartamento(Integer.parseInt(txtDepartamento.getText()));

    	
    	System.out.println(empleado.toString());
    	
    	boolean rsp = this.empleadoDao.registrarempleado(empleado);
    	
   	 if(rsp) {
			 Alert alert = new Alert (Alert.AlertType.INFORMATION);
			 alert.setTitle("Operacion correcta");
			 alert.setHeaderText(null);
			 alert.setContentText("Empresa registrada correctamente :)");
			 alert.initStyle(StageStyle.UTILITY);
			 alert.showAndWait();
			 
		 } else {
			 Alert alert = new Alert(Alert.AlertType.ERROR);
			 alert.setTitle("Operacion incorrecta");
			 alert.setHeaderText(null);
			 alert.setContentText("Revise la informacion");
			 alert.initStyle(StageStyle.UTILITY);
			 alert.showAndWait();
			 
		 }	
	}
}
