package application;

import javafx.fxml.FXML;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

public class Page3Controller {
	@FXML
	private TextField txtNombreEmp;
	@FXML
	private TextField txtApellidoPaterno;
	@FXML
	private TextField txtNombreEmp13;
	@FXML
	private TextField txtNombreEmp14;
	@FXML
	private TextField txtNombreEmp131;
	@FXML
	private TextField txtNombreEmp132;
	@FXML
	private TextField txtNombreEmp1311;
	@FXML
	private TextField txtNombreEmp1;
	@FXML
	private TextField txtNombreEmp11;
	@FXML
	private TextField txtNombreEmp12;
	@FXML
	private TextField txtNombreEmp121;

	// Event Listener on Button.onAction
	@FXML
	public void btnGuardarEmpleadoOnAction(ActionEvent event) {
		// TODO Autogenerated
	}
}
