package application;

import javafx.fxml.FXML;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

public class Page4Controller {
	@FXML
	private TextField txtNombreEmp;
	@FXML
	private TextField txtApellidoPaterno;
	@FXML
	private TextField txtApellidoMaterno;
	@FXML
	private TextField txtDepartamento;
	@FXML
	private TextField txtApellidoMaterno1;

	// Event Listener on Button.onAction
	@FXML
	public void btnGuardarEmpleadoOnAction(ActionEvent event) {
		// TODO Autogenerated
	}
}
