package application;

import javafx.fxml.FXML;

import javafx.scene.control.Label;

import javafx.scene.input.MouseEvent;

public class panelController {
	@FXML
	private Label login;

	// Event Listener on Button.onMouseClicked
	@FXML
	public void especies(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onMouseClicked
	@FXML
	public void proyectos(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onMouseClicked
	@FXML
	public void areas(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onMouseClicked
	@FXML
	public void personal(MouseEvent event) {
		// TODO Autogenerated
	}
}
